// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9UG1R2MO5eoZkJkqEhpxC-JeFgf6FuY',
    appId: '1:1062989714632:web:31a2d02fc99bdcd8ad41fd',
    messagingSenderId: '1062989714632',
    projectId: 'social-app-280e5',
    authDomain: 'social-app-280e5.firebaseapp.com',
    storageBucket: 'social-app-280e5.appspot.com',
    measurementId: 'G-NYEGGTCDQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQMWMAjeduugCnOT1aVU1QRBKGkN4hOk',
    appId: '1:1062989714632:android:4581b74915695ac6ad41fd',
    messagingSenderId: '1062989714632',
    projectId: 'social-app-280e5',
    storageBucket: 'social-app-280e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzFHBADYf3V8pjMt11iaQY6GSUPEZ1MBQ',
    appId: '1:1062989714632:ios:56bf2d64091cfcdead41fd',
    messagingSenderId: '1062989714632',
    projectId: 'social-app-280e5',
    storageBucket: 'social-app-280e5.appspot.com',
    iosBundleId: 'com.example.c2Movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzFHBADYf3V8pjMt11iaQY6GSUPEZ1MBQ',
    appId: '1:1062989714632:ios:56bf2d64091cfcdead41fd',
    messagingSenderId: '1062989714632',
    projectId: 'social-app-280e5',
    storageBucket: 'social-app-280e5.appspot.com',
    iosBundleId: 'com.example.c2Movil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu9UG1R2MO5eoZkJkqEhpxC-JeFgf6FuY',
    appId: '1:1062989714632:web:18e80a38ca6d0e27ad41fd',
    messagingSenderId: '1062989714632',
    projectId: 'social-app-280e5',
    authDomain: 'social-app-280e5.firebaseapp.com',
    storageBucket: 'social-app-280e5.appspot.com',
    measurementId: 'G-PBMF38XPZ9',
  );
}
